name: Run Tests

# This workflow is triggered on pull requests to the main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14' # Specify the Node.js version

    - name: Install Dependencies
      run: npm install

    - name: Run Tests
      run: npm test
